kcalendarcore: Autospec creation for update from version 5.115.0 to version 6.0.0
Alexander Lohnau (1):
      Remove code for generating pri file

Allen Winter (1):
      src/incidence.cpp - fix infinite looping

Anant Verma (1):
      resolve two warnings

Damien Caliste (1):
      Avoid calling twice update() in setAttendees().

Daniel Vrátil (1):
      ICalFormat: don't shift all-day invite dates to UTC

David Faure (1):
      Port to ECMFeatureSummary

Friedrich W. H. Kossebau (8):
      Update LINK_QCHS to Qt6 versions
      Use classic header guards consistently
      Use "= delete" to disable default copy assignment operator
      Mark pimpl constructors of public classes as unexported
      Generate version header on src/ level
      Have export macros header include version header
      Add explicit moc includes to sources for moc-covered headers
      Remove unneeded setting CMP0053 to NEW, implied by requiring CMake 3.16

Heiko Becker (1):
      GIT_SILENT Upgrade Qt6 version requirement to 6.5.0.

Jonathan Esk-Riddell (9):
      Update version number for 5.245.0
      Update version number for 5.246.0
      Update version number for 5.247.0
      update version for new release
      update version for new release
      update version for new release
      update version for new release
      update version for new release
      update version for new release

Julius Künzel (3):
      [tests] Fix undefined reference to qMain(int, char**)
      Fix non-void return
      Fix one more non-void return

Laurent Montel (4):
      Remove QT_STRINGIFY as we depend against qt6
      Use Q_RELOCATABLE_TYPE instead of deprecated Q_MOVABLE_TYPE
      GIT_SILENT: Remove mention of qmake library from metainfo.yaml
      GIT_SILENT: Port to new CI template

Nicolas Fella (5):
      Remove Qt5 CI
      Require Qt6
      Update KF_VERSION for KF6 development
      Rename CMake targets/config/libraries for KF6
      Bump KF_DEP_VERSION for KF6

Sune Vuorela (1):
      Fixup qHash

Volker Krause (21):
      Add Q_PROPERTY for IncidenceBase::url as well
      Bump Qt deprecation level to 6.4
      Remove deprecated API
      Remove Qt 5 support
      Remove the unused deletion tracking feature
      Remove MemoryCalendar::alarmsTo, already defined in the base class
      Replace QVector by QList
      Remove the no longer needed QVector variants of QMultiHash::values
      Use properly typed list properties
      Remove unused and non-functional save/reload/isSaving methods
      Fold Calendar::close() into the Calendar dtor
      Remove notebook support
      Remove Calendar relations API
      Use explicit lambda captures
      Create UUID in the right format to begin with
      Prepare the identical check for the effects of QDateTime API deprecation
      Port away from deprecated QDateTime API
      Port away from deprecated QHash API
      Port incidencestest to QtTest and make it actually work
      Port testtostring.cpp to QtTest
      Port testfb to QtTest as well